server:
  port: 8081
  jsp-servlet:
    init-parameters:
      development: true
  context-path: maven-boot
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useUnicode=true&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: 123456
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  mapper-locations: com.zn.maven.dao/*Dao.xml